# Generated by Django 5.2.5 on 2025-08-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colmeia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('temperatura', models.DecimalField(decimal_places=2, help_text='Temperatura em °C', max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso em kg', max_digits=6)),
                ('umidade', models.DecimalField(decimal_places=2, help_text='Umidade em %', max_digits=5)),
            ],
        ),
    ]
