# Generated by Django 5.2.4 on 2025-08-24 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_observacao', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('colmeia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='dashboard.colmeia')),
            ],
        ),
    ]
