# Generated by Django 5.2.5 on 2025-08-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_colmeia_owner_registro_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='colmeia',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
