# Generated by Django 5.2.5 on 2025-08-30 23:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_producao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producao',
            name='abelhas',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='mel',
        ),
        migrations.AddField(
            model_name='producao',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='producao',
            name='numero_abelhas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producao',
            name='quantidade_mel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producao',
            name='mes',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='producao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
