# Generated by Django 5.2.5 on 2025-08-27 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colmeia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('temperatura', models.DecimalField(decimal_places=2, help_text='Temperatura em °C', max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso em kg', max_digits=6)),
                ('umidade', models.DecimalField(decimal_places=2, help_text='Umidade em %', max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_colmeias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_observacao', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('colmeia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='accounts.colmeia')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_registros', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
