# Generated by Django 5.2.5 on 2025-08-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_colmeia_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='colmeia',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Colmeia',
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
